# Funding for AAC Board Viewer

This open-source project develops tools for the AAC (Augmentative and Alternative Communication) community.

## Sponsors

If you or your organization benefit from this project, please consider sponsoring its development.

## Donations

- GitHub Sponsors: [Link to be added]
- PayPal: [Link to be added]
- Patreon: [Link to be added]

## Acknowledgments

This project is built on top of the excellent [@willwade/aac-processors](https://github.com/willwade/AACProcessors-nodejs) library.

Thank you to all contributors who help make AAC tools more accessible!
